In [8]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 2.6 MB/s eta 0:00:0000:0100:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [2]:
!pip install spacy

Collecting spacy
  Downloading spacy-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.2/29.2 MB 2.4 MB/s eta 0:00:0000:0100:01
Collecting thinc<8.4.0,>=8.3.4
  Downloading thinc-8.3.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 4.4 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from spacy) (4.67.1)
Requirement already satisfied: setuptools in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from spacy) (59.6.0)
Collecting spacy-legacy<3.1.0,>=3.0.11
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.12-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.3/124.3 KB 3.6 MB/s eta 0:00:00
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (204 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.8/204.8 KB 1.6 MB/s eta 0:00:00a 0:00:01
Collecting langcodes<4.0.0,>=3.2.0
  Downloading langcodes-3.5.0-py3-none-any.whl (182 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.0/183.0 KB 4.3 MB/s eta 0:00:00a 0:00:01
Collecting catalogue<2.1.0,>=2.0.6
  Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Collecting weasel<0.5.0,>=0.1.0
  Downloading weasel-0.4.1-py3-none-any.whl (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.3/50.3 KB 1.7 MB/s eta 0:00:00ta 0:00:01
Requirement already satisfied: numpy>=1.19.0 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from spacy) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from spacy) (2.32.3)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4
  Downloading pydantic-2.10.6-py3-none-any.whl (431 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 431.7/431.7 KB 1.0 MB/s eta 0:00:00a 0:00:01
Collecting typer<1.0.0,>=0.3.0
  Downloading typer-0.15.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.9/44.9 KB 2.8 MB/s eta 0:00:00
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.9/156.9 KB 5.3 MB/s eta 0:00:00
Collecting spacy-loggers<2.0.0,>=1.0.0
  Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Collecting srsly<3.0.0,>=2.4.3
  Downloading srsly-2.5.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.8 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: jinja2 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from spacy) (3.1.5)
Requirement already satisfied: packaging>=20.0 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from spacy) (24.2)
Collecting wasabi<1.2.0,>=0.9.1
  Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Collecting language-data>=1.2
  Downloading language_data-1.3.0-py3-none-any.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 5.1 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: typing-extensions>=4.12.2 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Collecting pydantic-core==2.27.2
  Downloading pydantic_core-2.27.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 3.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.12.14)
Collecting blis<1.3.0,>=1.2.0
  Downloading blis-1.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 3.7 MB/s eta 0:00:0000:0100:01
Collecting confection<1.0.0,>=0.0.1
  Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Collecting shellingham>=1.3.0
  Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Collecting rich>=10.11.0
  Downloading rich-13.9.4-py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.4/242.4 KB 4.1 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: click>=8.0.0 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.8)
Collecting smart-open<8.0.0,>=5.2.1
  Downloading smart_open-7.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 KB 3.4 MB/s eta 0:00:00
Collecting cloudpathlib<1.0.0,>=0.7.0
  Downloading cloudpathlib-0.20.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 KB 2.8 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from jinja2->spacy) (3.0.2)
Collecting marisa-trie>=1.1.0
  Downloading marisa_trie-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 4.4 MB/s eta 0:00:00a 0:00:01
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 KB 1.7 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/ega/Documents/Reaserch/Ai-Generative/venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.1)
Collecting wrapt
  Downloading wrapt-1.17.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 KB 2.6 MB/s eta 0:00:0000:01
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: cymem, wrapt, wasabi, spacy-loggers, spacy-legacy, shellingham, pydantic-core, murmurhash, mdurl, marisa-trie, cloudpathlib, catalogue, blis, annotated-types, srsly, smart-open, pydantic, preshed, markdown-it-py, language-data, rich, langcodes, confection, typer, thinc, weasel, spacy
Successfully installed annotated-types-0.7.0 blis-1.2.0 catalogue-2.0.10 cloudpathlib-0.20.0 confection-0.1.5 cymem-2.0.11 langcodes-3.5.0 language-data-1.3.0 marisa-trie-1.2.1 markdown-it-py-3.0.0 mdurl-0.1.2 murmurhash-1.0.12 preshed-3.0.9 pydantic-2.10.6 pydantic-core-2.27.2 rich-13.9.4 shellingham-1.5.4 smart-open-7.1.0 spacy-3.8.4 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.1 thinc-8.3.4 typer-0.15.1 wasabi-1.1.3 weasel-0.4.1 wrapt-1.17.2

In [4]:
import spacy
import pandas as pd

In [9]:
nlp = spacy.load("en_core_web_sm")

In [10]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"
emma_ja

'emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own'

In [18]:
spacy_doc = nlp(emma_ja)

In [19]:
pos_df = pd.DataFrame(columns=['token' , 'pos_tag'])

In [20]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df , pd.DataFrame.from_records([{'token' : token.text , 'pos_tag' : token.pos_}])] , ignore_index=True)

In [21]:
pos_df.head(15)

          token pos_tag
0          emma   PROPN
1     woodhouse   PROPN
2      handsome     ADJ
3        clever     ADJ
4           and   CCONJ
5          rich     ADJ
6          with     ADP
7             a     DET
8   comfortable     ADJ
9          home    NOUN
10          and   CCONJ
11        happy     ADJ
12  disposition    NOUN
13       seemed    VERB
14           to    PART

In [22]:
post_df_counts = pos_df.groupby(['token', 'pos_tag']).size().reset_index(name='counts').sort_values(by='counts' , ascending=False)

In [23]:
post_df_counts

          token pos_tag  counts
88           of     ADP      14
54          her    PRON       9
49          had     AUX       9
6           and   CCONJ       8
111         the     DET       8
..          ...     ...     ...
124         who    PRON       1
127   woodhouse   PROPN       1
128  woodhouses   PROPN       1
129       world    NOUN       1
131    youngest     ADJ       1

[132 rows x 3 columns]

In [27]:
pos_df_postcounts = post_df_counts.groupby(['pos_tag'])['token'].count().sort_values(ascending=False)

In [28]:
pos_df_postcounts.head(10)

pos_tag
NOUN     35
VERB     19
ADJ      18
ADV      18
PRON      9
ADP       8
PROPN     6
DET       5
AUX       4
CCONJ     3
Name: token, dtype: int64

In [31]:
nouns = post_df_counts[post_df_counts.pos_tag == 'NOUN'][:10]
nouns

         token pos_tag  counts
48   governess    NOUN       3
46      friend    NOUN       3
130      years    NOUN       2
28   daughters    NOUN       2
35        emma    NOUN       2
82      mother    NOUN       2
103    sisters    NOUN       2
1    affection    NOUN       1
11   authority    NOUN       1
32    distress    NOUN       1

In [32]:
adj = post_df_counts[post_df_counts.pos_tag == 'ADJ'][:10]
adj

           token pos_tag  counts
70        little     ADJ       2
2   affectionate     ADJ       1
34         early     ADJ       1
44          fond     ADJ       1
39     excellent     ADJ       1
51         happy     ADJ       1
16          best     ADJ       1
25        clever     ADJ       1
26   comfortable     ADJ       1
63     indulgent     ADJ       1